src/beans/Comment.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int userId;
    private int messageId;
    private String text;
    private Date createdDate;
    private Date updatedDate;

    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public int getMessageId() {
		return messageId;
	}
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getCreated_date() {
		return createdDate;
	}
	public void setCreated_date(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}

src/beans/Message.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int userId;
    private String category;
    private String subject;
    private String text;
    private Date createDate;


    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getCreatedDate() {
		return createDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createDate = createdDate;
	}


}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		String loginId = request.getParameter("loginId");
		String password = request.getParameter("password");


		List<String> messages = new ArrayList<String>();

		LoginService loginService = new LoginService();
		User user = loginService.login(loginId, password);

		User loginMissUser = new User();
		loginMissUser.setLoginId(loginId);
		loginMissUser.setPassword(password);


		if(isValid(request, messages) == true){
			if (user != null && user.getIsWorking() != 1) {

				session.setAttribute("loginUser", user);
				response.sendRedirect("./");
			} else {

				messages.add("ログインに失敗しました");
				request.setAttribute("errorMessages", messages);
				request.setAttribute("loginMissUser", loginMissUser);
				request.getRequestDispatcher("/login.jsp").forward(request, response);
			}


		} else {

			messages.add("ログインに失敗しました");
			request.setAttribute("errorMessages", messages);
			request.setAttribute("loginMissUser", loginMissUser);

			request.getRequestDispatcher("/login.jsp").forward(request, response);
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String loginId = request.getParameter("loginId");
		String password = request.getParameter("password");


		if (StringUtils.isBlank(loginId) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!loginId.matches("[0-9a-zA-Z]{6,20}")) {
			messages.add("ログインIDは半角英数字で6文字以上20文字以内で入力してください");
		}
		if (StringUtils.isBlank(password) == true) {
			messages.add("パスワードを入力してください");
		} else if (!password.matches("[-_@+*;:#$%&A-Za-z0-9]{6,20}")) {
			messages.add("パスワードは記号を含む全ての半角文字で6文字以上20文字以内で入力してください");
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/SettingsServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Department;
import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.BranchService;
import service.DepartmentService;
import service.SettingsService;
import service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
        List<Branch> branches = new BranchService().getBranchLst();
        List<Department> departments = new DepartmentService().getDepartmentLst();
		List<String> messages = new ArrayList<String>();
//		User loginUser = (User) session.getAttribute("loginUser");

		String checkUserId = (request.getParameter("user.id"));
		System.out.println(checkUserId);
		if(checkUserId != null && checkUserId.length() != 0 && checkUserId.matches("^[0-9]*$")) {


		int getUserId  = Integer.parseInt(checkUserId);
		User user = new UserService().getUser(getUserId);

		if(user != null) {

			User editUser = new SettingsService().setting(getUserId);

		request.setAttribute("editUser", editUser);
        request.setAttribute("branches", branches);
        request.setAttribute("departments", departments);

		request.getRequestDispatcher("settings.jsp").forward(request, response);
		} else {
			messages.add("存在しないIDです");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("userLst");
		}

		} else {
			messages.add("存在しないIDです");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("userLst");
		}

	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User editUser = getEditUser(request);
	    String passwordCheck = request.getParameter("passwordCheck");

        List<Branch> branches = new BranchService().getBranchLst();
        List<Department> departments = new DepartmentService().getDepartmentLst();

        request.setAttribute("departments", departments);
        request.setAttribute("branches", branches);

		if (isValid(editUser, messages,passwordCheck) == true) {

			try {
				new UserService().update(editUser);
			} catch (NoRowsUpdatedRuntimeException e) {
				messages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
				session.setAttribute("errorMessages", messages);
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("settings.jsp").forward(request, response);
				return;
			}

			session.setAttribute("editUser", editUser);
			response.sendRedirect("userLst");
		} else {
			session.setAttribute("errorMessages", messages);
			editUser.setBranchId(editUser.getBranchId());
			editUser.setDepartmentId(editUser.getDepartmentId());
			request.setAttribute("editUser", editUser);

			request.getRequestDispatcher("settings.jsp").forward(request, response);
		}
	}

	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setLoginId(request.getParameter("loginId"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setName(request.getParameter("name"));
		editUser.setBranchId(Integer.parseInt(request.getParameter("branchId")));
		editUser.setDepartmentId(Integer.parseInt(request.getParameter("departmentId")));
		editUser.setIsWorking(Integer.parseInt(request.getParameter("isWorking")));
		return editUser;
	}


	private boolean isValid(User editUser, List<String> messages ,String passwordCheck) {

		String loginId = editUser.getLoginId();
		String name = editUser.getName();
		int branchId = editUser.getBranchId();
	    int departmentId = editUser.getDepartmentId();
	    String password = editUser.getPassword();

	    User user = new UserService().getUserSerch(loginId);


		if(StringUtils.isBlank(name) == true) {
			messages.add("名前を入力してください");
		} else if (10 < name.length()) {
			messages.add("名前は10文字以内入力してください");
		}
		if (StringUtils.isBlank(loginId) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!loginId.matches("[0-9a-zA-Z]{6,20}")) {
			messages.add("ログインIDは半角英数字で6文字以上20文字以内で入力してください");
		}
		if (!password.equals(passwordCheck)) {
			messages.add("パスワードが確認用パスワードと一致していません");
		}

		if (branchId == 0){
			messages.add("部署を選択してください");
		}
		if (departmentId == 0) {
			messages.add("役職を選択してください");
		}
		if(branchId != 100 && departmentId == 1 || branchId != 100 && departmentId == 2) {
			messages.add("不正な組み合わせです");
		}
		if(branchId == 100 && departmentId == 3 || branchId == 100 && departmentId == 4) {
			messages.add("不正な組み合わせです");
		}
		if(user != null && editUser.getId() != user.getId()) {
			messages.add("既に使われているIDです");
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/SignUpServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Department;
import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;


@WebServlet(urlPatterns = {"/signup"})
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

        List<Branch> branches = new BranchService().getBranchLst();
        List<Department> departments = new DepartmentService().getDepartmentLst();

        request.setAttribute("branches", branches);
        request.setAttribute("departments", departments);

		request.getRequestDispatcher("signup.jsp").forward(request, response);

	}


	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException{

        List<Branch> branches = new BranchService().getBranchLst();
        List<Department> departments = new DepartmentService().getDepartmentLst();

        request.setAttribute("branches", branches);
        request.setAttribute("departments", departments);

		List<String> messages = new ArrayList<>();

		HttpSession session = request.getSession();
		String passwordCheck = request.getParameter("passwordCheck");

		User signUpUser = new User();
		signUpUser.setName(request.getParameter("name"));
		signUpUser.setPassword(request.getParameter("password"));
		signUpUser.setLoginId(request.getParameter("loginId"));
		signUpUser.setBranchId(Integer.parseInt(request.getParameter("branchId")));
		signUpUser.setDepartmentId(Integer.parseInt(request.getParameter("departmentId")));

		if(isValid(request, messages,passwordCheck) == true) {

			new UserService().register(signUpUser);
			response.sendRedirect("userLst");

		} else {

			messages.add("登録に失敗しました");
			request.setAttribute("signUpUser", signUpUser );
			request.setAttribute(passwordCheck, passwordCheck);
			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("signup.jsp").forward(request, response);

		}
	}


	private boolean isValid(HttpServletRequest request, List<String> messages, String passwordCheck) {
		String loginId = request.getParameter("loginId");
		String name = request.getParameter("name");
		String password = request.getParameter("password");
		int branchId = Integer.parseInt(request.getParameter("branchId"));
		int departmentId = Integer.parseInt(request.getParameter("departmentId"));

	    User user = new UserService().getUserSerch(loginId);

		if(StringUtils.isBlank(name) == true) {
			messages.add("名前を入力してください");
		} else if (10 < name.length()) {
			messages.add("名前は10文字以内入力してください");
		}
		if (StringUtils.isBlank(loginId) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!loginId.matches("[0-9a-zA-Z]{6,20}")) {
			messages.add("ログインIDは半角英数字で6文字以上20文字以内で入力してください");
		}
		if (StringUtils.isBlank(password) == true) {
			messages.add("パスワードを入力してください");
		} else if (!password.matches("[-_@+*;:#$%&A-Za-z0-9]{6,20}")) {
			messages.add("パスワードは記号を含む全ての半角文字で6文字以上20文字以内で入力してください");
		}
		if(!password.equals(passwordCheck)) {
			messages.add("パスワードと確認用パスワードが一致していません");
		}
		if(branchId == 0) {
			messages.add("支店名を選択してください");
		}
		if(departmentId == 0) {
			messages.add("部署を選択してください");
		}
		if(branchId != 100 && departmentId == 1 || branchId != 100 && departmentId == 2) {
			messages.add("不正な組み合わせです");
		}
		if(branchId == 100 && departmentId == 3 || branchId == 100 && departmentId == 4) {
			messages.add("不正な組み合わせです");
		}
		if(user != null) {
			messages.add("既に使われているIDです");
		}
			if (messages.size() == 0 ) {
				return true;
			}else {
				return false;
			}
	}
}

src/controller/TopServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.UserComment;
import beans.UserMessage;
import service.CommentService;
import service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		String start = request.getParameter("start");
		String end = request.getParameter("end");
		String category = request.getParameter("category");


		List<UserMessage> messages = new MessageService().getMessage(start, end, category);

		request.setAttribute("messages", messages);

		List<UserComment> comments = new CommentService().getComment();
		request.setAttribute("comments", comments);

		request.setAttribute("start", start);
		request.setAttribute("end", end);
		request.setAttribute("category", category);

		request.getRequestDispatcher("/top.jsp").forward(request, response);

	}
}

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>ログイン</title>
</head>
<body>

	<div class="loginform">
		<h2 class="login-header">LOG IN</h2>

		<div class="login-container">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>

			<c:if test="${ not empty loginError }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${loginError}" var="loginError">
							<li><c:out value="${loginError}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="loginError" scope="session" />
			</c:if>

			<c:choose>
				<c:when test="${loginMissUser != null}">
					<form action="login" method="post">
						<label for="loginId">Login ID</label>
						<input name="loginId" value="${loginMissUser.loginId}" /><br />
						<label for="password">password</label>
						<input name="password" type="password" value="${loginMissUser.password}" /><br />
						<div class="submitButton">
							<input type="submit" class="button" value="Log in" /> <br />
						</div>
					</form>
				</c:when>

				<c:otherwise>
					<form action="login" method="post"><br />
						<label for="loginId">Log in</label>
						<input name="loginId" id="loginId" /> <br />
						<label for="password">password</label>
						<input name="password" type="password"  id="password" /> <br />
						<div class="submitButton">
							<input type="submit" class="button" value="Log in" /> <br />
						</div>
					</form>
				</c:otherwise>
			</c:choose>
			<div class="copyright">Copyright(c)ALH</div>
		</div>
	</div>
</body>
</html>

WebContent/messages.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html charset=UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>新規投稿</title>
</head>
<body>
<div class="main-contents">
	<div class="header">
		<ul class="headermenu">
			<c:choose>
				<c:when test="${not empty loginUser && loginUser.departmentId == 1}">
					<li><a href="./">ホーム</a></li>
					<li><a href="newMessage">新規投稿</a></li>
					<li><a href="userLst">ユーザ一覧</a></li>
					<li><a href="logout">ログアウト</a></li>
				</c:when>
				<c:otherwise>
					<li><a href="./">ホーム</a></li>
					<li><a href="newMessage">新規投稿</a></li>
					<li><a href="logout">ログアウト</a></li>
				</c:otherwise>
			</c:choose>
		</ul>
	</div>

	<div class="maincontent">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="errormessage">
						<li><c:out value="${errormessage}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>


		<div class="form-area">
			<form action="newMessage" method="post">

				<c:choose>
					<c:when test="${ not empty message}">
						<label for="subject">件名を入力してください</label>
						<input name="subject" type="text" value="${message.subject}" />
						<br />
						<label for="category">カテゴリを入力してください</label>
						<input name="category" type="text" value="${message.category}" />
						<br />本文（1000文字まで）<br />
						<textarea name="text" cols="100" rows="10"><c:out
								value="${message.text}" />
				</textarea>
						<br />
				<input type="submit" value="投稿する" class="btn"><br />
						<br />
					</c:when>
					<c:otherwise>
						<label for="subject">件名（30文字まで）</label>
						<input name="subject" type="text" />
						<br />
						<label for="category">カテゴリ（10文字まで）</label>
						<input name="category" type="text" />
						<br />本文（1000文字まで）<br />
						<textarea name="text" cols="100" rows="10"></textarea>
						<br />
						<input type="submit" value="投稿する" class="btn"><br />
					</c:otherwise>
				</c:choose>

			</form>
		</div>
	</div>
	<div class="copyright">Copyright(c)ALH</div>
</div>
</body>
</html>

WebContent/top.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE htmlPUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html charset=UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>掲示板</title>
</head>

<body>
	<div class="main-contents">
		<div class="header">
			<ul class="headermenu">
				<c:choose>
					<c:when
						test="${not empty loginUser && loginUser.departmentId == 1}">
						<li><a href="./">ホーム</a></li>
						<li><a href="newMessage">新規投稿</a></li>
						<li><a href="userLst">ユーザ一覧</a></li>
						<li><a href="logout">ログアウト</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="./">ホーム</a></li>
						<li><a href="newMessage">新規投稿</a></li>
						<li><a href="logout">ログアウト</a></li>
					</c:otherwise>
				</c:choose>
			</ul>
		</div>

		<div class="maincontent">

			<div class="errormessage">
				<c:if test="${not empty accesserror}">
					<div class="accesserror">
						<ul>
							<c:forEach items="${accesserror}" var="accesserror">
								<li><c:out value="${accesserror}" />
							</c:forEach>
						</ul>
					</div>
					<c:remove var="accesserror" scope="session" />
				</c:if>

				<c:if test="${not empty errorMessages}">
					<div class="errorMessages">
						<ul>
							<c:forEach items="${errorMessages}" var="message">
								<li><c:out value="${message}" />
							</c:forEach>
						</ul>
					</div>
					<c:remove var="errorMessages" scope="session" />
				</c:if>

				<c:if test="${ not empty accesserror }">
					<div class="accesserror">
						<ul>
							<c:forEach items="${accesserror}" var="accesserror">
								<li><c:out value="${accesserror}" />
							</c:forEach>
						</ul>
					</div>
					<c:remove var="accesserror" scope="session" />
				</c:if>
			</div>

			<div class="serch">
				<form action="./" method="get">
					<input type="date" name="start" value="${start}" class="dateserch"> ～ <input
						type="date" name="end" value="${end}" class="dateserch"><br /> <input
						type="text" name="category" value="${category}" /> <input
						type="submit" value="検索" class="btn">
				</form>
			</div>

			<c:forEach items="${messages}" var="message">
				<div class="message">
					<div class="text">
						<div class="subject">
						【<c:out value="${message.subject}" />】</div>
						<p class="postUser">投稿者：<c:out value="${message.name}" /></p>
						<p class="category">カテゴリ：<c:out value="${message.category}" /></p>
						<div class="date">
							<fmt:formatDate value="${message.createdDate}"
								pattern="yyyy/MM/dd HH:mm:ss" />
						</div>
						<div class="maintext">
						<pre><c:out value="${message.text}" /></pre>
						<c:if test="${loginUser.id == message.userId}">
							<form action="deleteMessage" method="post"
								onSubmit="return check()">
								<input type="hidden" name="message.id" value="${message.id}">
								<input type="submit" value="削除" class="btn">
							</form>
						</c:if>
						</div>
					</div>

					<div class="comments">
						<c:forEach items="${comments}" var="comment">
							<div class="comment">
								<c:if test="${comment.messageId == message.id}">
									<p class="postUser">投稿者：<c:out value="${comment.name}" /></p>
									<div class="date">
										<fmt:formatDate value="${comment.created_date}"
											pattern="yyyy/MM/dd HH:mm:ss" />
									</div>
									<pre><c:out value="${comment.text}" /></pre>
									<c:if test="${loginUser.id == comment.userId}">
										<form action="deleteComment" method="post"
											onSubmit="return check()">
											<input type="hidden" name="comment.id" value="${comment.id}">
											<input type="submit" value="削除" class="btn">
										</form>
									</c:if>
								</c:if>
							</div>
						</c:forEach>


						コメント（500文字まで）
						<form action="comments" method="post">
							<textarea name="text" cols="100" rows="5"></textarea>
							<br /> <input type="hidden" name="message.id"
								value="${message.id}"> <input type="hidden" name="text"
								value="text"> <input type="submit" value="投稿" class="btn">
						</form>
					</div>
				</div>
			</c:forEach>
		</div>
		<div class="copyright">Copyright(c)ALH</div>

		<script>
			function check() {

				if (window.confirm('削除しますか？')) {
					return true;
				} else {
					window.alert('キャンセルされました');
					return false;
				}
			}
		</script>
	</div>
</body>
</html>